version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.docker
    ports:
      - 80:3007
    depends_on:
      - backend
      - encryptor
      - geth
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
    tty: true
  encryptor:
    build:
      context: .
      dockerfile: encryptor.docker
    volumes:
      - ./encryptor:/var/www/encryptor
  backend:
    build:
      context: .
      dockerfile: backend.docker
    working_dir: /var/www/api
    ports:
      - 3004:3004
    volumes:
      - ./backend:/var/www/api
  geth:
    build:
      context: .
      dockerfile: geth.docker
    ports:
      - 4545:8545
