version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    depends_on:
      - backend
     # - encryptor
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
    env_file:
      - .env
    ports:
    - ${REACT_APP_PRODUCTION_PORT}:${REACT_APP_PRODUCTION_PORT}
    tty: true
    network_mode: host
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ${MEDIA_ATTACHMENTS_DIRECTORY}
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5433:5433"
    restart: unless-stopped
 # encryptor:
 #   build:
 #     context: .
 #     dockerfile: encryptor.docker
 #   volumes:
 #     - ./encryptor:/var/www/encryptor
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /var/www/api
    volumes:
      - ./backend:/var/www/api
      - ${NEDB_DIRECTORY}
      - ${LOCAL_FILES_DIRECTORY}
    env_file:
      - .env
    ports:
    - ${DATA_VALIDATOR_API_PORT}:${DATA_VALIDATOR_API_PORT}
    network_mode: host
    depends_on:
      - postgres
volumes:
  pg-data: {}
